import type {
  AiAgent,
  ModelProfile,
  RoutingRule,
  StoreSnapshot,
  Workspace,
} from "@lumina/core";
import { nowIso } from "@lumina/core";

export const DEFAULT_AGENTS: AiAgent[] = [
  {
    id: "chatgpt_lumina",
    name: "ChatGPT / LUMINA",
    role: "戦略 / PM / オーケストレーター",
    bestFor: ["計画", "要件", "振り分け判断"],
    dailySoftCapRp: 80,
    weeklySoftCapRp: 400,
    active: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    role: "探索 / 日常開発",
    bestFor: ["UI", "探索", "小さな修正", "CRUD"],
    dailySoftCapRp: 100,
    weeklySoftCapRp: 500,
    active: true,
  },
  {
    id: "claude_code",
    name: "Claude Code",
    role: "シニア実装 / アーキテクト",
    bestFor: ["認証", "DB", "設計", "複雑実装"],
    dailySoftCapRp: 80,
    weeklySoftCapRp: 400,
    active: true,
  },
  {
    id: "codex",
    name: "Codex",
    role: "レビュアー / デバッガー / 独立検証",
    bestFor: ["レビュー", "セキュリティ", "デバッグ", "回帰"],
    dailySoftCapRp: 80,
    weeklySoftCapRp: 400,
    active: true,
  },
];

const CHATGPT_EFFORT = "低 / 中 / 高 / 極高 / ウルトラ（GPT-5.5 は極高まで）";
const CLAUDE_EFFORT = "低 / 中 / 高 / 超高 / 最大 / ultracode";

export const DEFAULT_MODEL_PROFILES: ModelProfile[] = [
  {
    id: "mp_cursor_fast",
    agentId: "cursor",
    tier: "fast",
    label: "Composer 2.5 Fast",
    pickerModel: "Composer 2.5 Fast",
    pickerEffort: null,
    effortMenu: "Cursorのモデル一覧から選ぶ",
    providerModelHint: "composer-2.5-fast",
    active: true,
  },
  {
    id: "mp_cursor_balanced",
    agentId: "cursor",
    tier: "balanced",
    label: "Composer 2 / Auto",
    pickerModel: "Composer 2 / Auto",
    pickerEffort: null,
    effortMenu: "Cursorのモデル一覧から選ぶ",
    providerModelHint: "composer-2",
    active: true,
  },
  {
    id: "mp_cursor_strong",
    agentId: "cursor",
    tier: "strong",
    label: "Claude Sonnet 4.6（Cursor内）",
    pickerModel: "Claude Sonnet 4.6",
    pickerEffort: null,
    effortMenu: "Cursorのモデル一覧から選ぶ",
    providerModelHint: "claude-4.6-sonnet-medium-thinking",
    active: true,
  },
  {
    id: "mp_cursor_max",
    agentId: "cursor",
    tier: "max",
    label: "Claude Opus 4.6 Max Mode",
    pickerModel: "Claude Opus 4.6",
    pickerEffort: "Max Mode",
    effortMenu: "Cursorのモデル一覧 + Max Mode",
    providerModelHint: "claude-opus-4-6-max",
    active: true,
  },
  {
    id: "mp_claude_fast",
    agentId: "claude_code",
    tier: "fast",
    label: "Haiku 4.5",
    pickerModel: "Haiku 4.5",
    pickerEffort: null,
    effortMenu: "仕事量なし（Haikuはスライダー非対応）",
    providerModelHint: "claude-haiku-4-5",
    active: true,
  },
  {
    id: "mp_claude_balanced",
    agentId: "claude_code",
    tier: "balanced",
    label: "Sonnet 5 · 高",
    pickerModel: "Sonnet 5",
    pickerEffort: "高",
    effortMenu: CLAUDE_EFFORT,
    providerModelHint: "claude-sonnet-5",
    active: true,
  },
  {
    id: "mp_claude_strong",
    agentId: "claude_code",
    tier: "strong",
    label: "Opus 5 · 超高",
    pickerModel: "Opus 5",
    pickerEffort: "超高",
    effortMenu: CLAUDE_EFFORT,
    providerModelHint: "claude-opus-5",
    active: true,
  },
  {
    id: "mp_claude_max",
    agentId: "claude_code",
    tier: "max",
    label: "Fable 5.1 · 最大",
    pickerModel: "Fable 5.1",
    pickerEffort: "最大",
    effortMenu: CLAUDE_EFFORT,
    providerModelHint: "claude-fable-5-1",
    active: true,
  },
  {
    id: "mp_codex_fast",
    agentId: "codex",
    tier: "fast",
    label: "GPT-5.6 Luna · 低",
    pickerModel: "GPT-5.6 Luna",
    pickerEffort: "低",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-luna",
    active: true,
  },
  {
    id: "mp_codex_balanced",
    agentId: "codex",
    tier: "balanced",
    label: "GPT-5.6 Terra · 中",
    pickerModel: "GPT-5.6 Terra",
    pickerEffort: "中",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-terra",
    active: true,
  },
  {
    id: "mp_codex_strong",
    agentId: "codex",
    tier: "strong",
    label: "GPT-5.6 Sol · 高",
    pickerModel: "GPT-5.6 Sol",
    pickerEffort: "高",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-sol",
    active: true,
  },
  {
    id: "mp_codex_max",
    agentId: "codex",
    tier: "max",
    label: "GPT-6 Astra · 極高",
    pickerModel: "GPT-6 Astra",
    pickerEffort: "極高",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-6-astra",
    active: true,
  },
  {
    id: "mp_lumina_fast",
    agentId: "chatgpt_lumina",
    tier: "fast",
    label: "GPT-5.6 Luna · 低",
    pickerModel: "GPT-5.6 Luna",
    pickerEffort: "低",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-luna",
    active: true,
  },
  {
    id: "mp_lumina_balanced",
    agentId: "chatgpt_lumina",
    tier: "balanced",
    label: "GPT-5.6 Terra · 中",
    pickerModel: "GPT-5.6 Terra",
    pickerEffort: "中",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-terra",
    active: true,
  },
  {
    id: "mp_lumina_strong",
    agentId: "chatgpt_lumina",
    tier: "strong",
    label: "GPT-5.6 Sol · 高",
    pickerModel: "GPT-5.6 Sol",
    pickerEffort: "高",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-5.6-sol",
    active: true,
  },
  {
    id: "mp_lumina_max",
    agentId: "chatgpt_lumina",
    tier: "max",
    label: "GPT-6 Astra · 極高",
    pickerModel: "GPT-6 Astra",
    pickerEffort: "極高",
    effortMenu: CHATGPT_EFFORT,
    providerModelHint: "gpt-6-astra",
    active: true,
  },
];

export const DEFAULT_ROUTING_RULES: RoutingRule[] = [
  {
    id: "rr_split_xl",
    name: "XL / 複雑度9以上は分割",
    priority: 100,
    condition: { minComplexity: 9 },
    result: {
      agent: "chatgpt_lumina",
      modelTier: "max",
      mode: "plan",
      splitRecommended: true,
    },
    active: true,
  },
  {
    id: "rr_review_codex",
    name: "レビュー/セキュリティ → Codex",
    priority: 90,
    condition: { taskTypes: ["review", "security"] },
    result: { agent: "codex", modelTier: "strong", mode: "review" },
    active: true,
  },
  {
    id: "rr_auth_strong",
    name: "認証/DBの高複雑度 → Claude Strong",
    priority: 70,
    condition: { domains: ["auth", "db", "security"], minComplexity: 6 },
    result: {
      agent: "claude_code",
      modelTier: "strong",
      reviewRequired: true,
      reviewAgent: "codex",
    },
    active: true,
  },
  {
    id: "rr_low_cursor",
    name: "低複雑度 → Cursor",
    priority: 10,
    condition: { maxComplexity: 3 },
    result: { agent: "cursor", modelTier: "fast" },
    active: true,
  },
];

export function createEmptyWorkspace(): Workspace {
  const t = nowIso();
  return {
    id: "ws_default",
    name: "LUMINA HQ",
    ownerName: "とみー",
    createdAt: t,
    updatedAt: t,
  };
}

export function createSeedStore(): StoreSnapshot {
  return {
    version: 1,
    workspace: createEmptyWorkspace(),
    projects: [],
    missions: [],
    tasks: [],
    taskDependencies: [],
    aiAgents: DEFAULT_AGENTS,
    modelProfiles: DEFAULT_MODEL_PROFILES,
    routingRules: DEFAULT_ROUTING_RULES,
    runs: [],
    usageEvents: [],
    handoffs: [],
    contextAssets: [],
    approvals: [],
    resourceOverrides: {
      chatgpt_lumina: { todayRp: 0, weekRp: 0, status: "green" },
      cursor: { todayRp: 0, weekRp: 0, status: "green" },
      claude_code: { todayRp: 0, weekRp: 0, status: "green" },
      codex: { todayRp: 0, weekRp: 0, status: "green" },
    },
  };
}
